apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-cleaner
  namespace: admin
spec:
  template:
    spec:
      containers:
        - name: drone-cleaner
          image: drone-cleaner:dev
          env:
            - name: GHOST_URL
              value: "http://blog.blog.svc.cluster.local"
            - name: LOG_LEVEL
              value: "DEBUG"

