apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-cleaner
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-cleaner
  template:
    metadata:
      labels:
        app: blog-cleaner
    spec:
      containers:
        - name: blog-cleaner
          image: blog-cleaner:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: GHOST_URL
              value: "http://blog.blog.svc.cluster.local"
            - name: GHOST_ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: blog-cleaner-secret
                  key: admin-api-key
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
