apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: blog-cleaner-scaler
  namespace: admin
spec:
  scaleTargetRef:
    name: blog-cleaner
    kind: Deployment
  minReplicaCount: 1
  maxReplicaCount: 3
  cooldownPeriod: 300
  pollingInterval: 30
  triggers:
    - type: cron
      metadata:
        timezone: UTC
        start: "0 0 * * *"      # Run at midnight UTC
        end: "5 0 * * *"        # Until 00:05 UTC
        desiredReplicas: "1"
