apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: api

patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml

configMapGenerator:
  - name: fastapi-env-config
    behavior: create
    files:
      - env-config.yaml

secretGenerator:
  - name: fastapi-secrets
    behavior: replace
    literals:
      - database-url=postgresql://fastapi:PASSWORD@postgres.api-dev.svc.cluster.local:5432/fastapi
      - api-key=dev-api-key-placeholder

commonLabels:
  environment: dev

images:
  - name: fastapi
    newName: dronedevneacr.azurecr.io/fastapi
    newTag: latest

replicas:
  - name: fastapi
    count: 1
