apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - ingress-patch.yaml

configMapGenerator:
  - name: blog-config
    literals:
      - environment=dev

vars:
  - name: KEYVAULT_NAME
    objref:
      kind: ConfigMap
      name: env-config
      apiVersion: v1
    fieldref:
      fieldpath: data.keyvault_name
  - name: TENANT_ID
    objref:
      kind: ConfigMap
      name: env-config
      apiVersion: v1
    fieldref:
      fieldpath: data.tenant_id
