apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-claim
  namespace: blog
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 50Gi

