apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-database-kv
  namespace: blog
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "${KEYVAULT_NAME}"
    objects: |
      array:
        - |
          objectName: database-host
          objectType: secret
          objectVersion: ""
        - |
          objectName: database-admin-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: database-admin-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: database-name
          objectType: secret
          objectVersion: ""
        - |
          objectName: database-ca-cert
          objectType: secret
          objectVersion: ""
    tenantId: "${TENANT_ID}"
  secretObjects:
    - secretName: database-connection
      type: Opaque
      data:
        - objectName: database-host
          key: database__connection__host
        - objectName: database-admin-username
          key: database__connection__user
        - objectName: database-admin-password
          key: database__connection__password
        - objectName: database-name
          key: database__connection__database
        - objectName: database-ca-cert
          key: database__connection__ssl__ca
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-smtp-kv
  namespace: blog
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "${KEYVAULT_NAME}"
    objects: |
      array:
        - |
          objectName: smtp-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: smtp-password
          objectType: secret
          objectVersion: ""
    tenantId: "${TENANT_ID}"
  secretObjects:
    - secretName: smtp-connection
      type: Opaque
      data:
        - objectName: smtp-username
          key: mail__options__auth__user
        - objectName: smtp-password
          key: mail__options__auth__pass

