apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret.yaml
  - scaled-object.yaml

commonLabels:
  app: fastapi
  app.kubernetes.io/name: fastapi
  app.kubernetes.io/part-of: api-platform

images:
  - name: fastapi
    newName: fastapi
    newTag: latest
