name: Build and deploy blog cleaner

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/blog-cleaner.yml
      - src/blog-cleaner/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/blog-cleaner.yml
      - src/blog-cleaner/**

jobs:
  python-lint:
    uses: ./.github/workflows/python-lint.yml
    with:
      working-directory: src/blog-cleaner

  k8s-lint:
    uses: ./.github/workflows/k8s-lint.yml
    with:
      base-path: kubernetes/blog-cleaner/base
      dev-overlay-path: kubernetes/blog-cleaner/overlays/dev

  build-and-deploy:
    needs:
      - python-lint
      - k8s-lint
    #if: github.event_name == 'push'
    uses: ./.github/workflows/aks-build-deploy.yml
    with:
      project-dir: ${{ github.workspace }}/src/blog-cleaner
      k8s-dir: ${{ github.workspace }}/kubernetes/blog-cleaner
      image-name: blog-cleaner
      namespace: admin
      deployment-name: blog-cleaner
    secrets:
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
