name: Build and deploy blog

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/blog.yml
      - kubernetes/blog/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/blog.yml
      - kubernetes/blog/**

jobs:
  lint:
    name: Lint Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.9.3
        with:
          kustomize: 5.0.3
          kubeconform: 0.6.3

      - name: Validate kustomize build
        run: |
          kustomize build kubernetes/blog/base --load-restrictor LoadRestrictionsNone | kubeconform -strict -summary

      - name: Validate dev overlay
        run: |
          kustomize build kubernetes/blog/overlays/dev --load-restrictor LoadRestrictionsNone | kubeconform -strict -summary

  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/ghost-cleaner/Dockerfile
          push: true
          tags: ${{ secrets.ACR_SERVER }}/ghost-cleaner:${{ env.BRANCH_NAME }}-${{ github.sha }}

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: 5.0.3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Set Azure credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Update image tag in kustomization.yaml
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENVIRONMENT="prod"
          else
            ENVIRONMENT="dev"
          fi
          
          # Update the image tag in the kustomization.yaml for the appropriate environment
          cd kubernetes/blog/overlays/$ENVIRONMENT
          kustomize edit set image ghost:5=ghost:5  # We're not changing the Ghost image, but would update any custom images here

      - name: Deploy to Kubernetes
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENVIRONMENT="prod"
          else
            ENVIRONMENT="dev"
          fi
          
          kustomize build kubernetes/blog/overlays/$ENVIRONMENT | kubectl apply -f -
          
          # Verify deployment
          kubectl rollout status deployment/blog -n blog --timeout=180s

