name: Build and deploy FastAPI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/fastapi.yml
      - src/fastapi/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/fastapi.yml
      - src/fastapi/**

jobs:
  python-lint:
    uses: ./.github/workflows/python-lint.yml
    with:
      working-directory: ${{ github.workspace }}/src/fastapi

  k8s-lint:
    uses: ./.github/workflows/k8s-lint.yml
    with:
      base-path: kubernetes/fastapi/base
      dev-overlay-path: kubernetes/fastapi/overlays/dev

  build-and-deploy:
    needs: [ python-lint, k8s-lint ]
    if: github.event_name == 'push'
    uses: ./.github/workflows/aks-build-deploy.yml
    with:
      project-dir: ${{ github.workspace }}/src/fastapi
      k8s-dir: ${{ github.workspace }}/kubernetes/fastapi
      image-name: fastapi
      namespace: api
      deployment-name: fastapi
    secrets:
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
