name: Build and Deploy Ghost Cleaner

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ghost-cleaner.yml
      - src/ghost-cleaner/*
  pull_request:
    branches:
      - main
    changes:
      - .github/workflows/ghost-cleaner.yml
      - src/ghost-cleaner/*

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      PROJECT_DIR: "${{ github.workspace }}/ghost-cleaner"
      IMAGE_NAME: ghost-cleaner

    steps:
      - name: Select environment
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "selected-environment=prd" >> "$GITHUB_ENV"
          else
            echo "selected-environment=dev" >> "$GITHUB_ENV"
          fi

      - name: Checkout
        uses: actions/checkout@v4

      #- name: Azure Login
      #  uses: azure/login@v2
      #  with:
      #    tenant-id: "${{ secrets.ARM_TENANT_ID }}"
      #    subscription-id: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
      #    client-id: "${{ secrets.ARM_CLIENT_ID }}"
      #    client-secret: "${{ secrets.ARM_CLIENT_SECRET }}"

      - name: Azure Login & Get AKS Credentials
        env:
          ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
        run: |
          az login \
          --service-principal \
          --username $ARM_CLIENT_ID \
          --password $ARM_CLIENT_SECRET \
          --tenant $ARM_TENANT_ID
          
          az account set \
          --subscription $ARM_SUBSCRIPTION_ID
          
          az aks get-credentials \
          --resource-group drone-${{env.selected-environment}}-ne-rg \
          --name drone-${{env.selected-environment}}-ne-k8s \
          --overwrite-existing

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ACR Login
        run: |
          ACR_NAME="drone${{env.selected-environment}}neacr"
          echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV
          az acr login --name $ACR_NAME

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./ghost-cleaner
          push: true
          tags: "${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest"

      - name: Setup kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update kustomization.yaml
        run: |
          cd "${{ github.workspace }}/ghost-cleaner/base"
          kustomize edit set image ghost-cleaner=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          kubectl create namespace blog --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -k ghost-cleaner/base
