on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - feature/*

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      AZURE_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
      AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
    steps:
      - name: Select environment
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "production"
            echo "selected-environment=prd" >> "$GITHUB_ENV"
          else
            echo "development"
            echo "selected-environment=dev" >> "$GITHUB_ENV"
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: |
          terraform init
          -input=false
          -backend-config subscription_id=${{secrets.AZURE_SUBSCRIPTION_ID}}
          -backend-config resource_group_name=terraform
          -backend-config storage_account_name=ncterraform
          -backend-config container_name=state
          -backend-config key=drone-${{env.DOCKER_IMAGE_NAME}}-northeurope.tfstate

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan
            -input=false
            --var project_name=drone
            --var location=northeurope
            --var-file .\${{env.DOCKER_IMAGE_NAME}}-northeurope.json
            -out=tfplan

      - name: Terraform Apply
        run: |
          terraform apply
            -input=false
            -auto-approve
            --var project_name=drone
            tfplan
            
