name: Deploy infra and configure k8s

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: Name of the project
        required: true
        default: drone
      location:
        description: Azure region for deployment
        required: true
        default: northeurope
  push:
    branches:
      - main
    paths:
      - .github/workflows/infrastructure.yml
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/infrastructure.yml
      - terraform/**

jobs:
  validate-infra:
    name: Validate Infrastructure
    uses: ./.github/workflows/terraform-validate.yml
    with:
      working_directory: "${{ github.workspace }}/terraform/infra"
      backend_key_suffix: -northeurope
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  validate-k8s:
    name: Validate Kubernetes
    uses: ./.github/workflows/terraform-validate.yml
    with:
      working_directory: "${{ github.workspace }}/terraform/k8s"
      backend_key_suffix: -k8s-northeurope
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

  infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs:
      - validate-infra
      - validate-k8s
    env:
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
      PROJECT_WORKING_DIR: "${{ github.workspace }}/terraform/infra"
      PROJECT_NAME: "${{ github.event.inputs.project_name }}"
      LOCATION: "${{ github.event.inputs.location }}"
    steps:
      - name: Select environment
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "production"
            echo "selected-environment=prd" >> "$GITHUB_ENV"
          else
            echo "development"
            echo "selected-environment=dev" >> "$GITHUB_ENV"
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: >
          terraform init
          -input=false
          -backend-config="subscription_id=$ARM_SUBSCRIPTION_ID"
          -backend-config="resource_group_name=terraform"
          -backend-config="storage_account_name=ncterraform"
          -backend-config="container_name=state"
          -backend-config="key=${PROJECT_NAME}-${{env.selected-environment}}-${LOCATION}.tfstate"
        working-directory: "${{ env.PROJECT_WORKING_DIR }}"

      - name: Terraform Plan
        run: >
          terraform plan
          -input=false
          --var="project_name=${PROJECT_NAME}"
          --var="location=${LOCATION}"
          -out=tfplan
        working-directory: "${{ env.PROJECT_WORKING_DIR }}"

      - name: Terraform Apply
        #if: github.ref_name == 'main'
        run: >
          terraform apply
          -input=false
          tfplan
        working-directory: "${{ env.PROJECT_WORKING_DIR }}"

  k8s:
    name: Deploy Kubernetes
    runs-on: ubuntu-latest
    needs:
      - infra
    env:
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
      PROJECT_WORKING_DIR: "${{ github.workspace }}/terraform/k8s"
      PROJECT_NAME: "${{ github.event.inputs.project_name }}"
      LOCATION: "${{ github.event.inputs.location }}"
    steps:
      - name: Select environment
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "production"
            echo "selected-environment=prd" >> "$GITHUB_ENV"
          else
            echo "development"
            echo "selected-environment=dev" >> "$GITHUB_ENV"
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: kubelogin
        env:
          ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
        run: |
          az login \
          --service-principal \
          --username $ARM_CLIENT_ID \
          --password $ARM_CLIENT_SECRET \
          --tenant $ARM_TENANT_ID
          
          az account set \
          --subscription $ARM_SUBSCRIPTION_ID
          
          # Define resource group name
          RESOURCE_GROUP="${PROJECT_NAME}-${{env.selected-environment}}-${LOCATION}-rg"
          echo "Resource group: $RESOURCE_GROUP"
          
          # Get the first AKS cluster in the resource group
          AKS_NAME=$(az aks list --resource-group $RESOURCE_GROUP --query "[0].name" -o tsv)
          echo "AKS cluster found: $AKS_NAME"
          
          # Get credentials using the discovered AKS name
          az aks get-credentials \
          --context k8s \
          --resource-group $RESOURCE_GROUP \
          --name $AKS_NAME \
          --overwrite-existing

          kubelogin convert-kubeconfig -l azurecli

      - name: Terraform Init
        run: >
          terraform init
          -input=false
          -backend-config="subscription_id=$ARM_SUBSCRIPTION_ID"
          -backend-config="resource_group_name=terraform"
          -backend-config="storage_account_name=ncterraform"
          -backend-config="container_name=state"
          -backend-config="key=${PROJECT_NAME}-${{env.selected-environment}}-k8s-${LOCATION}.tfstate"
        working-directory: "${{ env.PROJECT_WORKING_DIR }}"

      - name: Terraform Plan
        run: >
          terraform plan
          -input=false
          --var="project_name=${PROJECT_NAME}"
          --var="location=${LOCATION}"
          -out=tfplan
        working-directory: "${{ env.PROJECT_WORKING_DIR }}"

      - name: Terraform Apply
        #if: github.ref_name == 'main'
        run: >
          terraform apply
          -input=false
          tfplan
        working-directory: "${{ env.PROJECT_WORKING_DIR }}"
