name: Kubernetes Manifest Validation

on:
  workflow_call:
    inputs:
      base-path:
        required: true
        type: string
        description: 'Base path for kustomize build'
      dev-overlay-path:
        required: true
        type: string
        description: 'Path to dev overlay for kustomize build'

jobs:
  k8s-lint:
    name: Lint Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.9.3
        with:
          kustomize: 5.0.3
          kubeconform: 0.6.3

      - name: Validate kustomize build
        run: |
          kustomize build ${{ inputs.base-path }} --load-restrictor LoadRestrictionsNone | kubeconform -strict -summary

      - name: Validate dev overlay
        run: |
          kustomize build ${{ inputs.dev-overlay-path }} --load-restrictor LoadRestrictionsNone | kubeconform -strict -summary
