name: Kubernetes Lint

on:
  workflow_call:
    inputs:
      base-path:
        required: true
        type: string
      dev-overlay-path:
        required: true
        type: string

jobs:
  lint:
    name: Lint Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: 5.0.3

      - name: Install Kubeconform
        run: |
          curl -L -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/download/v0.6.3/kubeconform-linux-amd64.tar.gz
          tar xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/

      - name: Validate base manifests
        run: |
          kustomize build ${{ inputs.base-path }} --load-restrictor LoadRestrictionsNone | kubeconform -strict -summary -skip "SecretProviderClass,ScaledObject"

      - name: Validate dev overlay manifests
        run: |
          kustomize build ${{ inputs.dev-overlay-path }} --load-restrictor LoadRestrictionsNone | kubeconform -strict -summary -skip "SecretProviderClass,ScaledObject"
