name: Python Linting and Testing

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: 'The directory where Python code is located'

jobs:
  python-lint:
    name: Python Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies with pipenv
        working-directory: ${{ inputs.working-directory }}
        run: |
          pipenv install --dev

      - name: Generate requirements.txt from Pipfile
        working-directory: ${{ inputs.working-directory }}
        run: |
          pipenv requirements > requirements.txt
          echo "Generated requirements.txt file:"
          cat requirements.txt

      - name: Run ruff linter
        working-directory: ${{ inputs.working-directory }}
        run: |
          pipenv install ruff
          pipenv run ruff check .

      - name: Run pylint
        working-directory: ${{ inputs.working-directory }}
        run: |
          pipenv install pylint
          pipenv run pylint *.py

      - name: Run mypy type checking
        working-directory: ${{ inputs.working-directory }}
        run: |
          pipenv install mypy
          pipenv run mypy .

      - name: Run pytest with coverage
        working-directory: ${{ inputs.working-directory }}
        run: |
          pipenv install pytest pytest-cov
          pipenv run pytest --cov=. --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ${{ inputs.working-directory }}/coverage.xml
          fail_ci_if_error: false
