name: Terraform Validation

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
        description: "The directory containing Terraform files to validate"
      backend_key_suffix:
        required: true
        type: string
        description: "The suffix for state file key (e.g., -northeurope or -k8s-northeurope)"
    secrets:
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    env:
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      PROJECT_WORKING_DIR: ${{ inputs.working_directory }}
    steps:
      - name: Select environment
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "production"
            echo "selected-environment=prd" >> "$GITHUB_ENV"
          else
            echo "development"
            echo "selected-environment=dev" >> "$GITHUB_ENV"
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Checkov GitHub Action
        continue-on-error: true
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli
          output_file_path: console
          quiet: true
          soft_fail: true
          directory: "${{ env.PROJECT_WORKING_DIR }}"

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: "${{ env.PROJECT_WORKING_DIR }}"

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
        run: >
          terraform init
          -input=false
          -backend-config="subscription_id=$ARM_SUBSCRIPTION_ID"
          -backend-config="resource_group_name=terraform"
          -backend-config="storage_account_name=ncterraform"
          -backend-config="container_name=state"
          -backend-config="key=drone-${{env.selected-environment}}${{ inputs.backend_key_suffix }}.tfstate"
        working-directory: "${{ env.PROJECT_WORKING_DIR }}"

      - name: Terraform Validate
        run: terraform validate
        working-directory: "${{ env.PROJECT_WORKING_DIR }}"
